# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-04 03:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='datasets',
            fields=[
                ('datasetid', models.AutoField(db_column='datasetid', primary_key=True, serialize=False)),
                ('dataname', models.CharField(blank=True, db_column='dataname', max_length=32, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='seriesnames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriesname', models.CharField(blank=True, db_column='seriesname', max_length=32, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=256, null=True)),
                ('datasettid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exploredata.datasets')),
            ],
        ),
        migrations.CreateModel(
            name='timeseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriesname', models.CharField(blank=True, db_column='seriesname', max_length=32, null=True)),
                ('value', models.FloatField(blank=True, db_column='value', null=True)),
                ('date', models.DateTimeField(db_column='datetime')),
                ('datasettid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exploredata.datasets')),
            ],
        ),
    ]
