# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-07 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploredata', '0003_auto_20160907_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsmodelworkflow',
            name='AR',
            field=models.IntegerField(db_column='AR', default=0),
        ),
        migrations.AddField(
            model_name='tsmodelworkflow',
            name='I',
            field=models.IntegerField(db_column='I', default=0),
        ),
        migrations.AddField(
            model_name='tsmodelworkflow',
            name='MA',
            field=models.IntegerField(db_column='MA', default=0),
        ),
    ]
